# Generated by Django 4.2.1 on 2023-05-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_remove_formation_pdf_formation_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='excel_file',
            field=models.FileField(null=True, upload_to='excels/'),
        ),
        migrations.AddField(
            model_name='formation',
            name='word_file',
            field=models.FileField(null=True, upload_to='words/'),
        ),
    ]
