# Generated by Django 4.2.1 on 2023-05-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_formation_excel_file_formation_word_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='excels/'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to='words/'),
        ),
    ]
